### ISSUE TITLE
2. ACME flow

### ISSUE THREAD

**Issue by mikemaxey** [smallstep/docs-old#101]
https://smallstep.notion.site/Use-ACME-with-Certificate-Manage-3add740028fe49569ce9c4a9f28291ce

https://raw.githubusercontent.com/smallstep/certificates/master/scripts/install-step-ra.sh

- [x] RA explainer
- [x] Install configure RA
- [x] Link RA to Certificate Manager
- [ ] issue test cert?
- [x] Connect clients to RA
- [x] Get cert
- [ ] inspect cert
- [ ] Configure renewal
- [ ] alerts and events. 
https://smallstep.slack.com/archives/C01RANSM020/p1626365402002300

**Comment by tashian** [comment]
This will be a tutorial that lives under Certificate Manager docs section

**Comment by devadvocado** [comment]
Waiting for script by @tashian

**Comment by tashian** [comment]
I think this is done, as of https://github.com/smallstep/docs/commit/4fd6ad6a69d8169460739fa0777f76e8a51dcb81.  I've tested the install script on a fresh EC2 instance with our CM beta team CA.

@pizzasaurusrex you may want to glance at this commit, as I made some changes to the manual instructions too. Specifically, there is no "ra fingerprint" (it's the same as the CA fingerprint), so I removed that and changed the references to it.
