### ISSUE TITLE
Challenge anchor (overview link) incorrect

### ISSUE THREAD

**Issue by strarsis** [smallstep/docs-old#115]
The `Challenge` link uses an anchor for which no element of that ID exists.

Documentation page: https://smallstep.com/docs/tutorials/acme-challenge

Link `Challenges` in that page [overview](https://smallstep.com/docs/tutorials/acme-challenge#overview) is the anchor `#challenges`. However, it doesn't work as there is no element with corresponding ID `challenges`.
Instead the `ACME challenges` heading element that belongs to that referred section has the ID `acme-challenges` (the anchor-symbol next to it copies the correct anchor into clipboard (https://smallstep.com/docs/tutorials/acme-challenge#acme-challenges)).

**Comment by devadvocado** [comment]
Thanks for reporting it @strarsis, fix it!
