### ISSUE TITLE
Document cosign sig verification process

### ISSUE THREAD

**Issue by tashian** [smallstep/docs-old#117]
via @dopey:

We released a change today that will add signatures for each artifact generated by goreleaser during the release process (see https://github.com/smallstep/certificates/releases/tag/v0.17.2). We’re using [cosign](https://github.com/sigstore/cosign) to generate the signatures. We should add some documentation about how users can go about verifying the signatures. It’s as easy as running the following command: `cosign verify-blob -key cosign.pub -signature file.tar.gz.sig file.tar.gz` where `cosign.pub` is a pub key found at the root of the cli and certificates repos (we’re using different keys for each repo). I’m not sure where to add this bit of documentation, so thought I might let y’all (carl & kevin) decide. Let me know if you need any more info.

**Comment by tashian** [comment]
@devadvocado my hunch is that these instructions should live in the "test your installation" section of the install docs for step and step-ca. does that sound right? if so, could you add them please?

**Comment by tashian** [comment]
Alternatively, this bit of info could live as a static piece of content in the release notes for every new version, eg on https://github.com/smallstep/certificates/releases/tag/v0.17.2. I _think_ the way to do this would be to add a `header` to the `goreleaser.yml` under the [release](https://goreleaser.com/customization/release) section.

**Comment by dopey** [comment]
I think I like it in the goreleaser.yml. I hate to say it, but we may want it in both. There are folks who may go direct to the github releases and others who may go to the installation docs on the website.

**Comment by dopey** [comment]
Documented in github release headers and on the dockerhub READMEs for cli and certificates.
