### ISSUE TITLE
Better description for `instance-age` parameter

### ISSUE THREAD

**Issue by dopey** [smallstep/docs-old#12]

**Comment by mmalone** [comment]
The language in question is:

    The maximum duration to grant a certificate in AWS and GCP provisioners.

I propose the following alternative language:

    The maximum age of an instance that should be allowed to obtain a certificate using the AWS
    and GCP provisioners. Limits certificate issuance to new instances to mitigate the risk of 
    credential-misuse from instances that don't need a certificate.
