### ISSUE TITLE
Document security characteristics of IID provisioners more precisely

### ISSUE THREAD

**Issue by mmalone** [smallstep/docs-old#13]
Our [documentation of IID provisioners](https://smallstep.com/docs/step-ca/configuration#trust-on-first-use) imply that our single-use-per-instance control "allows the use of more permissive certificate signing requests that can have custom SANs that cannot be validated". This statement implies something that's not generally true: that you can fully trust the identity bound to a certificate even though it's client-supplied and never authenticated.

The reality is, by default, IID provisioners allow any instance to get a certificate with any name. So _every instance_ must be trusted. In our default configuration users shouldn't assume anything more than a "cryptographic perimeter": if a client/server can present a certificate you can have some confidence that it's part of your infrastructure (it's one of your instances), but you really have very little assurance that the bound name is authentic.

We do provide a couple additional mechanisms that strengthen these security characteristics:

  1. If you disable custom SANs (set `"disableCustomSANs": true`) then the CA will only issue certificates with authentic name(s) extracted from the signed instance identity document. The downside is that these authentic names are internal instance names and may not be the names that you use to refer to your servers and services.
  2. If you set the max instance age and your infrastructure is setup such that some trusted process (e.g., config management) is run on startup _on every instance_ to "consume" the instance identity document and obtain a certificate with a legitimate name then you may have more assurance that the bound names in certificates are legitimate. Keep in mind that, in this model, instances that don't obtain a certificate are a risk: anyone with access to such an instance will be able to obtain a certificate binding any name so long as the instance is younger than _max instance age_. There are a lot of details to get right to make this model secure, many of which are environment-dependent and beyond the scope of this document.

Let's update our docs to say something like the above. We probably need some wordsmithing, but I think I've captured all of the important details.

**Comment by alanchrt** [comment]
@tashian Some security issues were raised yesterday... maybe you could take a stab at this docs update? Just clarification of our security limitations on IID provisioners.
