### ISSUE TITLE
step-ca location discrepancies

### ISSUE THREAD

**Issue by maraino** [smallstep/docs-old#46]
### Description

If you follow the `step-ca` installation instructions and instructions for configuring the systemd service, the service will fail because the install instructions puts the binary in /usr/bin, while the systemd uses the binary in /usr/local/bin. 

We should remove all those discrepancies.

**Comment by maraino** [comment]
The user that found that suggested me to add a note to disable sandboxing while troubleshooting, the errors provided by systemd were quite confusing.

**Comment by dopey** [comment]
I've just changed the default location in the systemd example file in the certificates repo.

**Comment by dopey** [comment]
With regards to the changing how sandboxing works, sandbox is meant to make the service more secure. We don't want to reduce security to make up for systemd's poor error output.

So, we've added a `NOTE` above the sandboxing section in the systemd that asks user's to comment out the section if they are trouble shooting. 🤷
