### ISSUE TITLE
The removal documentation of step-cli and step-ca is missing.

### ISSUE THREAD

**Issue by khashashin** [smallstep/docs-old#66]
I can't find a stroke of how to remove step-cli and step-ca from my Ubuntu machine. 😑

**Comment by dopey** [comment]
Hey @khashashin thanks for opening the issue! We definitely need to add this.

Out of curiosity, how did you install `step` / `step-ca`? If it's a debian package it should be as easy as running `sudo apt-get uninstall [step | step-ca]`, and then `rm -rf $STEPPATH`. Similarly with a tarball you'd want to remove the files left by unzipping, and then remove the `STEPPATH`. More or less the same for other distros. But we definitely should have directions in our docs.

**Comment by khashashin** [comment]
@dopey  thx for the reply. I've followed the instructions on the step Dokumentation: https://smallstep.com/docs/step-ca/installation#debian and did the following:

Install step
Download and install the Debian package from our latest release:
```
wget https://github.com/smallstep/cli/releases/download/v0.15.14/step-cli_0.15.14_amd64.deb
sudo dpkg -i step-cli_0.15.14_amd64.deb
```

Install step-ca
Download and install the Debian package from our latest release:
```
wget https://github.com/smallstep/certificates/releases/download/v0.15.11/step-ca_0.15.11_amd64.deb
sudo dpkg -i step-ca_0.15.11_amd64.deb
```

**Comment by tashian** [comment]
Hi @khashashin, you can remove these by running

`sudo dpkg -r step-cli step-ca`

and remove the `~/.step` configuration directory.

**Comment by tashian** [comment]
Keeping this issue open pending some uninstall instructions in the docs.
